name: "whisper_b30a6af63b3440a291083b93da70cf67"
backend: "python"
input [
  {
    name: "audio_url"
    data_type: TYPE_STRING	
    dims: [-1]
  }
]
output [
  {
    name: "transcribed_text"
    data_type: TYPE_STRING	
    dims: [-1]
  }
]

instance_group [
  {
    kind: KIND_GPU
  }
]

